version: "3"

services:

  #
  # Database
  #
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "somedb"
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_USER: "someusername"
      MYSQL_PASSWORD: "somepassword"
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

  #
  # API
  #
  api:
    image: directus/api:latest
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: "somedb"
      DATABASE_USERNAME: "someusername"
      DATABASE_PASSWORD: "somepassword"
      ADMIN_EMAIL: "admin@localhost.com"
      ADMIN_PASSWORD: "directusrocks"
    ports:
      - 7000:80
    depends_on:
      - db

  #
  # Dashboard
  #
  app:
    image: directus/app:latest
    environment:
      API_ENDPOINT: "API; http://localhost:7000/_/"
    ports:
      - 8000:80
    depends_on:
      - api

  #
  # Adminer
  #
  adminer:
    image: adminer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db: